# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10
language: swift
podfile: Example/Podfile

# cache: cocoapods
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example

env:
  - ACTION=test  PLATFORM=macOS     DESTINATION='platform=macOS'   SCHEME=QNStringCrypto-Mac
  - ACTION=test  PLATFORM=iOS     DESTINATION='platform=iOS Simulator,name=iPhone XS'   SCHEME=QNStringCrypto-Example

script:
  - set -o pipefail && xcodebuild -workspace Example/QNStringCrypto.xcworkspace -scheme "$SCHEME" -destination "$DESTINATION" $ACTION | xcpretty
